version: '3'

networks:
  app-network:
    driver: bridge

services:
  carbohelm:
    image: carbo-helm
    env_file: .env
    networks:
      - app-network
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    