#!/usr/bin/env bash

###########################
# Release to dockerhub.
#
# Required variables:
#   DOCKERHUB_USERNAME
#   DOCKERHUB_PASSWORD
###########################

set -ex

DOCKERHUB_PASSWORD="!Carb0n1120"
DOCKERHUB_USERNAME="carbonetes"
IMAGE="carbonetes/carbonetes-analyzer"
VERSION=1.0.0

echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
docker build -t ${IMAGE} .
docker tag ${IMAGE} ${IMAGE}:${VERSION}
docker push ${IMAGE}
