export enum Common {
    ERROR                =   "ERROR ",
    INFO                 =   "INFO ",
    SUCCESS              =   "SUCCESS ",
    NOVULNFOUND          =   "No Vulnerabilities Found",
    NOLICENSEFOUND       =   "No Licenses Found",
    NOTHREATSFOUND       =   "No Threats Found",
    NOSECRETSFOUND       =   "No Secrets Found",
    NOPACKAGESFOUND      =   "No Packages Found",
    VULNERABILITIES      =   "vulnerabilities",
    ANALYSIS             =   "analysis",
    DEPENDENCIES         =   "dependencies",
    IMAGEDEPENDENCIES    =   "imageDependencies",
    SCANRESULT           =   "scanResult",
    INFECTEDFILES        =   "infectedFiles",
    SECRETS              =   "secrets",
    ARTIFACTS            =   "artifacts",
    NOPOLICYSELECTED     =   "No Policy Selected",
    NOACTIONSELECTED     =   "No Action Selected",
    POLICYRESULT         =   "POLICY RESULT: ",
    FINALACTION          =   "FINAL ACTION: ",
    NOREGISTRYFOUND      =   "Registry Is not found",
    NOIMAGEFOUND         =   "Image is not found in the registry",
    AUTHENTICATIONFAILED =   "Authentication Failed",
    NOACCOUNTFOUND       =   "Account not found",
    LICENSEEXPIRED       =   "License has already expired",
    INSUFFICIENTLICENSE  =   "Insufficient license count",
    RENEWLICENSELINK     =   "https://aws.amazon.com/marketplace/saas/ordering?productId=1bede3a0-aff1-4a89-ad92-baab6b8b4e70",
    EXECUTE              =   "Executing Carbonetes Complete Analysis",
    FINISHED             =   "Finished analyzing",
    RESULT               =   "Analysis Results:",
    IMAGE                =   "Image: ",
    STOPBUILD            =   "If you see this message, the carbonetes task stops the build because the image fail on policy evaluation",
    IMAGEERROR           =   "Image is not found in the registry",
    EXPIREDMSG           =   "Your contract licenses has expired",
    INSUFFMSG            =   "Your contract license is insufficient for your current users",
    RENEWMSG             =   "Please configure or renew your AWS Contract licenses at: ",
    AUTHMSG              =   ". Please check your username and password",
    FAILEDMSG            =   "failed to execute Carbonetes Comprehensive Analysis: ",
    MISSING_PASSWORD     =   "MISSING REQUIRED ENVIRONMENT VARIABLE: CARBONETES_PASSWORD",
    MISSING_USERNAME     =   "MISSING REQUIRED ENVIRONMENT VARIABLE: CARBONETES_USERNAME",
    ANALYSIS_API         =   "https://api.carbonetes.com/api/v1/analysis/analyze",
    RESULTS_API          =   "https://api.carbonetes.com/api/v1/analysis/get-result",
    NOTES                =   "Get the application URL by running these commands:" +
                             "\nkubectl --namespace <RELEASE-NAMESPACE> port-forward <POD_NAME> 3000:3000",
    NEXTLINE             =   "\n",
    TAB                  =   "\t",
}